server:
  port: 9999


spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/exams?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123455


mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 全局id类型为自增长
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰


knife4j:
  enable: true
  openapi:
    title: 在线考试系统接口文档
    description: "在线考试系统接口文档"
    email: 2052349409@qq.com
    concat: 何时去
    url: https://www.baiidu.com
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.examsservice.controller.admin

#exam:
#  alioss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: 
#    access-key-secret: 
#    bucket-name: wm-plus-images